import { createApp } from 'vue';
import App from './app.vue';
import { router } from './router';
// import '@assets/styles/common/resets.css';
import '@assets/styles/common/typoa.css';

import comHeading from './components/markdown/com-heading.vue';
import comParagraph from './components/markdown/com-paragraph.vue';
import comLink from './components/markdown/com-link.vue';
import comStrong from './components/markdown/com-strong.vue';
import comEmphasis from './components/markdown/com-emphasis.vue';
import comBlockquote from './components/markdown/com-blockquote.vue';
import comCode from './components/markdown/com-code.vue';
import comInlineCode from './components/markdown/com-inlineCode.vue';
import comList from './components/markdown/com-list.vue';
import comListItem from './components/markdown/com-listItem.vue';
import comThematicBreak from './components/markdown/com-thematicBreak.vue';
import comImage from './components/markdown/com-image.vue';
import comDelete from './components/markdown/com-delete.vue';
import comTable from './components/markdown/com-table.vue';
import comThead from './components/markdown/com-thead.vue';
import comTbody from './components/markdown/com-tbody.vue';
import comTableRow from './components/markdown/com-tableRow.vue';
import comTableCell from './components/markdown/com-tableCell.vue';
import home from './views/home/index.vue';

const app = createApp(App);

app.use(router);
app.component('comHeading', comHeading);
app.component('comParagraph', comParagraph);
app.component('comLink', comLink);
app.component('comStrong', comStrong);
app.component('comEmphasis', comEmphasis);
app.component('comBlockquote', comBlockquote);
app.component('comCode', comCode);
app.component('comInlineCode', comInlineCode);
app.component('comList', comList);
app.component('comListItem', comListItem);
app.component('comThematicBreak', comThematicBreak);
app.component('comImage', comImage);
app.component('comDelete', comDelete);
app.component('comTable', comTable);
app.component('comThead', comThead);
app.component('comTbody', comTbody);
app.component('comTableRow', comTableRow);
app.component('comTableCell', comTableCell);
app.component('home', home);

app.mount('#app');
